### ISSUE TITLE
Lifecycle - Remove of VNF instances

### ISSUE THREAD

**Issue by jbatalle** [T-NOVA/TeNOR#63]
When a VNF instance is removed, sometimes the Stack is removed from Openstack, but Openstack returns an error message. Then, the VNF Manager is not able to remove the Stack because no exists inside Openstack. The VNF instance should be removed after polling the Stack status.

**Comment by miguelcastilho** [comment]
Is this issue related to the error from mAPI?

**Comment by jbatalle** [comment]
Partially related, but basically is a job for the VNF Provisioning. When the Stack is removed from OpenStack (returns 404), the vnfr can be removed

**Comment by miguelcastilho** [comment]
The issue with mAPI is fixed here #67 
The VNFR is removed when the OpenStackfails to create the stacj or when the VNF Manager receives a request to remove a VNF. 
Is there any other scenario where the VNFR has to be removed?
