### ISSUE TITLE
Provisioning VNF fails, no Rundeck jobs created.

### ISSUE THREAD

**Issue by wnke** [T-NOVA/TeNOR#85]
Provisioning a VNF that needs a template file for the start/stop events containing the private, public and floating ip for each machine fails as no Rundeck job is created.

**Comment by jbatalle** [comment]
TeNOR read the Output field from the VNFD and inserts to the Heat template. If these fields are incorrect, the heat template will return an empty output for each one of these fields.

So, TeNOR can avoid call the mAPI (and return a Provisioning Error) if one of these fields are empty.

**Comment by wnke** [comment]
In the start event of the "lifecycle_info", for the problematic request we can find this:

 "template_file": "{\"controller\":\"get_attr[CPino4, fixed_ips, 0, ip_address]\", \"vdu1net0\":\"get_attr[CPtg9p, fixed_ips, 0, ip_address]\", \"vdu1net1\":\"get_attr[CPo2n2, fixed_ips, 0, ip_address]\"}",

So there is the info required to know what the controller's ip. Is the controller field not in the right place?

**Comment by jbatalle** [comment]
The problem is the response from openstack; the get_attr[CPo2n2, fixed_ips, 0, ip_address] is null.

**Comment by wnke** [comment]
Doing a  curl -v  http://10.10.1.61:4572/vnf-provisioning/vnf-instances/57448d92b18cfb5308000005

show that the following addresses are assign:  

"vnf_addresses": {
        "CPino4": null,
        "CPino4#floating_ip": "10.10.1.195",
        "CPo2n2": null,
        "CPo2n2#floating_ip": "10.10.1.188",
        "CPtg9p": null,
        "CPtg9p#floating_ip": "10.10.1.187"
    },

CPo2n2 is assign a floating IP. The controller IP is the CPino4, how would CPo2n2 being empty interfere with the controller IP?

**Comment by dbourasseau** [comment]
@wnke @jbatalle @nherbaut we still don't have lifecycles event working. Rundeck job is created, but not executed. Once it's executed an error is caught
```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=.*, dominant=false, }}
    at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.validateNodeSet(NodeFirstWorkflowStrategy.java:341)
    at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:84)
    at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
    at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=.*, dominant=false, }}
No matched nodes: NodeSet{includes={name=.*, dominant=false, }}
```
